services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-qcontabil}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qcontabil}
      POSTGRES_DB: ${POSTGRES_DB:-qcontabil}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-test:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: qcontabil
      POSTGRES_PASSWORD: qcontabil
      POSTGRES_DB: qcontabil_test
    ports:
      - '5434:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
